<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJjyuzpf\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJjyuzpf/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJjyuzpf.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJjyuzpf\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJjyuzpf\appDevDebugProjectContainer();
